// <auto-generated />
namespace Sennit.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class di : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(di));
        
        string IMigrationMetadata.Id
        {
            get { return "201710291805228_di"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
